name: build-windows
on: [push, workflow_dispatch]
jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller
      - run: pyinstaller --onefile --uac-admin --name WSL-Compact app.py
      - uses: actions/upload-artifact@v4
        with:
          name: WSL-Compact
          path: dist/WSL-Compact.exe
