name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller==6.5.0
      - run: pyinstaller --onefile --uac-admin --name WSL-Compact app.py
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --title "WSL-Compact ${{ github.ref_name }}" --notes "Automated release of WSL-Compact executable. Download WSL-Compact.exe to compact your WSL2 VHDX files on Windows." ./dist/WSL-Compact.exe
